version: '2'
services:
  nginx:
    image: 923665038280.dkr.ecr.us-east-1.amazonaws.com/proxy:12
    mem_limit: 256000000
    ports:
      - "80:80"
      - "8888:8888"
      - "8002:8002"
      - "7002:7003"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: docker-gen -watch -notify "nginx" /app/nginx.tmpl /etc/nginx/conf.d/default.conf
    environment:
      - AWS_ELB=development-load-balancer-1144607924.us-east-1.elb.amazonaws.com
